### ISSUE TITLE
Crash on Android due to fresco class not found

### ISSUE THREAD

**Issue by andresteves** [ReactVision/viro#290]
# Requirements: 

Please go through this checklist before opening a new issue
  - [x] Review the [documentation](https://viro-community.readme.io/docs/overview)
  - [x] Search for existing issues in: [ViroCommunity/viro](https://github.com/ViroCommunity/viro/issues)
  - [x] Use the latest [ViroReact release](https://docs.viromedia.com/docs/releases)

## Environment

Please provide the following information about your environment:
1. Development OS: Mac,
2. Device OS & Version: What Android OS version (7.0, 8.0, etc.)  is your device running on? Android 13
3. Version: ViroReact 2.41.1 and React Native 0.68.7
4. Device(s): What device(s) are you are seeing the issue on (i.e. iPhone X, Samsung Note 8, etc) One plus 8

## Description

After upgrading Viro to the latest version I get whenever I try to start viro on the app

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/imagepipeline/image/BaseCloseableStaticBitmap;
at com.viromedia.bridge.utility.ImageDownloader$1.onNewResultImpl(ImageDownloader.java:156)
```

**Comment by tranminhnhat1005** [comment]
Same issue +1

**Comment by doranteseduardo** [comment]
Please share more context so I can help you.

**Comment by tranminhnhat1005** [comment]
In my case, I changed the version to 2.23.3 and the problem was solved.

`"@viro-community/react-viro": "2.23.3"`

> Same issue +1

**Comment by andresteves** [comment]
@doranteseduardo it happens with those versions above on original post and when I start Viro on the app. It happens when deploying on an Android 13 device.

**Comment by andresteves** [comment]
@tranminhnhat1005 Yes that version works but latest version updates android libraries and I believe is causing it to happen on the version of RN I originally said. I have updated RN to 0.73.0 and it does not happens anymore.

**Comment by tranminhnhat1005** [comment]
> @tranminhnhat1005 Yes that version works but latest version updates android libraries and I believe is causing it to happen on the version of RN I originally said. I have updated RN to 0.73.0 and it does not happens anymore.

Yes, I have some projects with different react-native versions, and which project using >=0.73.0 worked. I tried to finding the reason and found it:

https://reactnative.dev/blog/2023/12/06/0.73-debugging-improvements-stable-symlinks#other-breaking-changes:~:text=Android%3A%20Major%20bump%20of%20Fresco%20to%203.0%20(%2338275).
